### PR TITLE
File uploading and testing

### PR DESCRIPTION
**Pull request by samwilson**
**Don't merge until https://github.com/addwiki/mediawiki-api-base/pull/38 is resolved and a new release tagged.**

This adds some new backwards-compatible functionality for uploading
files, and adds to the testing and documentation.

Depends-On: https://github.com/addwiki/mediawiki-api-base/pull/38
Bug: https://phabricator.wikimedia.org/T176832

### CODE REVIEW

**Comment by addshore** [comment]
Needs a rebase!

**Comment by addshore** [comment]
For the file used in the fixture, what is the licence?
Could we use something like one of the below instead?

bluesq
greensq
redsq

**Comment by samwilson** [comment]
Good point about the file; I've replaced it with your blue image.

Also marked this as dependent on on 2.4.0 of addwiki/mediawiki-api-base so it'll fail till that's tagged.

**Comment by samwilson** [comment]
This is ready for review now, if anyone's got a chance.

**Pull request merged**
